format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$sudo\
$line_break\
$jobs\
$status\
$character"""

right_format = """
$cmd_duration\
$username\
$hostname\
$localip"""

[directory]
truncate_to_repo = false
truncation_length = 10

[hostname]
format = "@ [$hostname]($style) "
ssh_only = true

[localip]
disabled = false
format = "@ [$localipv4]($style)"

[sudo]
disabled = true

[username]
format = "[$user]($style) "
style_user = "bold green"

