format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$env_var\
$username\
$hostname\
$jobs\
$cmd_duration\
$status\
$line_break\
$character"""

[directory]
truncate_to_repo = false
truncation_length = 10
truncation_symbol = "..."

[git_commit]
tag_disabled = false

[hostname]
format = "@ [$hostname]($style) "
ssh_only = true

[status]
disabled = false

[username]
format = "[$user]($style) "
style_user = "bold green"
