local common = require('custom.common')
local plugin = require('custom.plugin-manager')
local options = require('custom.options')
local keymaps = require('custom.keymaps')
local whitespace = require('custom.whitespace')
local plain_term = require('custom.plain-term')
local neovide = require('custom.neovide')


common.set_leader_keys()
plugin.install_lazy_nvim()
plugin.register_plugins()
options.init()
keymaps.init()
whitespace.init()
plain_term.init()
neovide.init()
