#!/bin/sh

# Move the mouse to the centre of the active screen
#
# dotool is used instead of ydotool since it doesn't work well with monitor scaling.
# I would've liked to have replaced ydotool with dotool but dotool has its own issues such slow
# startup time and dotoold not working well.

echo mouseto 0.5 0.5 | dotool
