#!/bin/sh

# Helpers to transcribe an audio file to captions.

if [ $# -lt 1 ]; then
  echo "Usage: stt [download <URL>|whisper|transcribe]"
  exit 1
fi

CMD=$1
WAV_FILE="audio.wav"
VTT_FILE="audio.vtt"

if [ "$CMD" = "whisper" ]; then
  echo "Entering Whisper Nix shell..."
  nix shell nixpkgs#openai-whisper --offline --no-update-lock-file
elif [ "$CMD" = "download" ]; then
  if [ $# -lt 2 ]; then
    echo "Usage: stt download <URL>"
    exit 1
  fi

  URL=$2

  echo "Downloading file: $URL"
  yt-dlp --extract-audio --audio-format wav --output "$WAV_FILE" "$URL"
elif [ "$CMD" = "transcribe" ]; then
  echo "Converting audio to Whisper-friendly format..."
  ffmpeg -i "$WAV_FILE" -ar 16000 -ac 1 -c:a pcm_s16le audio16k.wav && mv audio16k.wav "$WAV_FILE"

  echo "Transcribing audio with Whisper..."
  whisper --language en --model base --word_timestamps True --max_line_count 1 --max_words_per_line 1 --output_format vtt "$WAV_FILE"

  echo "Stitching captions with Recap..."
  recap restitch $VTT_FILE | recap -i linger | recap -i fixup > final.vtt

  echo "Removing temp files..."
  rm "$WAV_FILE" "$VTT_FILE"

  echo "All done!"
else
  echo "Unknown sub-command: " "$CMD"
  exit 1
fi
