#!/usr/bin/env bash

# For viewing diffs, use Neovide in a graphical environment otherwise Neovim

LOCAL="$1"
REMOTE="$2"

if [ -n "$DISPLAY" ] && command -v neovide &> /dev/null; then
  neovide --no-tabs -- -c "DiffTool $LOCAL $REMOTE"
  exit 0
fi

nvim -c "DiffTool $LOCAL $REMOTE"
