#!/bin/sh

# Update wallpaper

set -eu

WALLPAPER_PATH=~/Pictures/wallpaper/bing.jpg

if [ -f $WALLPAPER_PATH ]; then
  swaybg --image $WALLPAPER_PATH
fi

bing-wallpaper.clj $WALLPAPER_PATH
swaybg --image $WALLPAPER_PATH
