#!/usr/bin/env bash

# Reload Waybar instances

killall waybar 2>/dev/null
waybar &
# NOTE: We sleep for a second to ensure that the main bar has time to fill the entire width of the screen
sleep 1s
waybar -c ~/.config/waybar/sidebar.jsonc -s ~/.config/waybar/sidebar.css
