# -*- conf -*-

# For documentation on these options, see `man fnott.ini`

# Global values
# output=<undefined>#
# min-width=0
# max-width=0
# max-height=0
# stacking-order=bottom-up
# anchor=top-right
edge-margin-vertical=30
edge-margin-horizontal=30
# notification-margin=10
icon-theme=elementary
# max-icon-size=32
# selection-helper=dmenu
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top
background=000000bb

border-color=00000000
border-radius=15
# border-size=1

# padding-vertical=20
# padding-horizontal=20

# dpi-aware=yes

# title-font=sans serif
# title-color=ffffffff
title-format=

summary-font=Maple Mono NL NF CN:size=12
# summary-color=ffffffff
summary-format=<b>%s</b>

body-font=Maple Mono NL NF CN:size=16
# body-color=ffffffff
# body-format=%b

# progress-bar-height=20
# progress-color=ffffffff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
max-timeout=3
# default-timeout=0
# idle-timeout=0

# [low]
# background=2b2b2bff
# title-color=888888ff
# summary-color=888888ff
# body-color=888888ff

# [normal]

# [critical]
# background=6c3333ff
