local lazy = require('config.lazy')
local options = require('config.options')
local keymaps = require('config.keymaps')
local whitespace = require('config.whitespace')
local kitty = require('config.kitty')
local lsp = require('config.lsp')
local neovide = require('config.neovide')

options.init()
keymaps.init()
whitespace.init()
lsp.init()
kitty.init()
neovide.init()
lazy.install()
lazy.register_plugins()
