local plugin = require('custom.plugin-manager')
local options = require('custom.options')
local keymaps = require('custom.keymaps')
local whitespace = require('custom.whitespace')
local kitty = require('custom.kitty')
local neovide = require('custom.neovide')

options.init()
keymaps.init()
whitespace.init()
kitty.init()
neovide.init()
plugin.install_lazy_nvim()
plugin.register_plugins()
